#!/bin/bash
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14
do
wget "ftp://ftp.ensembl.org/pub/release-99/fasta/ciona_intestinalis/dna/Ciona_intestinalis.KH.dna.chromosome."$i".fa.gz"
gunzip "Ciona_intestinalis.KH.dna.chromosome."$i".fa.gz"

done
