#!/bin/bash
for i in I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI
do
wget "ftp://ftp.ensembl.org/pub/release-99/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.chromosome."$i".fa.gz"
gunzip "Saccharomyces_cerevisiae.R64-1-1.dna.chromosome."$i".fa.gz"

done
