#!/bin/bash
for i in 2L 2R 3L 3R 4 X Y
do
wget "ftp://ftp.ensembl.org/pub/release-99/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.28.dna.chromosome."$i".fa.gz"
gunzip "Drosophila_melanogaster.BDGP6.28.dna.chromosome."$i".fa.gz"

done
