#!/bin/bash
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 W Z
do
wget "ftp://ftp.ensembl.org/pub/release-99/fasta/gallus_gallus/dna/Gallus_gallus.GRCg6a.dna.chromosome."$i".fa.gz"
gunzip "Gallus_gallus.GRCg6a.dna.chromosome."$i".fa.gz"

done
