#!/bin/bash
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X Y
do
wget "ftp://ftp.ensembl.org/pub/release-99/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.chromosome."$i".fa.gz"
gunzip "Mus_musculus.GRCm38.dna.chromosome."$i".fa.gz"

done
