#!/bin/bash                                                                     

especies=(homo_sapiens mus_musculus danio_rerio caenorhabditis_elegans ciona_intestinalis gallus_gallus drosophila_melanogaster saccharomyces_cerevisiae)
subfijos=(Homo_sapiens.GRCh38 Mus_musculus.GRCm38 Danio_rerio.GRCz11 Caenorhabditis_elegans.WBcel235 Ciona_intestinalis.KH Gallus_gallus.GRCg6a Drosophila_melanogaster.BDGP6.28 Saccharomyces_cerevisiae.R64-1-1)

for i in 0 1 2 3 4 5 6 7
do
wget "ftp://ftp.ensembl.org/pub/release-99/fasta/"${especies[$i]}"/cds/"${subfijos[$i]}".cds.all.fa.gz"
gunzip ${subfijos[$i]}".cds.all.fa.gz"

done
