#!/bin/bash                                                                                                                                                                                                 
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y
do
wget "ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome."$i".fa.gz"
gunzip "Homo_sapiens.GRCh38.dna.chromosome."$i".fa.gz"

done